language: rust
rust:
  - 1.20.0
os:
  - linux
  - osx
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin:$HOME/bin"
- rustup install nightly
- rustup run nightly cargo install --force rustfmt-nightly
- curl http://pre-commit.com/install-local.py | python
script:
- rustup run nightly rustfmt --version
- pre-commit run --all-files
- cargo build
- cargo test
